/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/linker/ng_module_factory';
import * as import1 from './quiz';
import * as import2 from '@angular/common/src/common_module';
import * as import3 from '@angular/forms/src/directives';
import * as import4 from '@angular/forms/src/form_providers';
import * as import5 from '@angular/common/src/localization';
import * as import6 from '@angular/forms/src/directives/radio_control_value_accessor';
import * as import7 from '@angular/core/src/di/injector';
import * as import8 from '@angular/core/src/i18n/tokens';
import * as import9 from '@angular/core/src/change_detection/change_detection_util';
import * as import10 from '@angular/core/src/linker/view';
import * as import11 from '@angular/core/src/linker/view_utils';
import * as import12 from '@angular/core/src/render/api';
import * as import13 from '@angular/core/src/metadata/view';
import * as import14 from '@angular/core/src/linker/view_type';
import * as import15 from '@angular/core/src/change_detection/constants';
import * as import16 from '@angular/core/src/linker/component_factory';
import * as import17 from '@angular/core/src/linker/view_container';
import * as import18 from '../../node_modules/@angular/common/src/directives/ng_if.ngfactory';
import * as import19 from '@angular/core/src/linker/template_ref';
import * as import20 from '@angular/common/src/directives/ng_if';
import * as import21 from '../../node_modules/@angular/common/src/directives/ng_class.ngfactory';
import * as import22 from '@angular/core/src/change_detection/differs/iterable_differs';
import * as import23 from '@angular/core/src/change_detection/differs/keyvalue_differs';
import * as import24 from '@angular/core/src/linker/element_ref';
import * as import25 from '@angular/common/src/directives/ng_class';
import * as import26 from '../../node_modules/@angular/common/src/directives/ng_for.ngfactory';
import * as import27 from '@angular/common/src/directives/ng_for';
import * as import28 from '../../node_modules/@angular/forms/src/directives/ng_form.ngfactory';
import * as import29 from '../../node_modules/@angular/forms/src/directives/ng_control_status.ngfactory';
import * as import30 from '@angular/forms/src/directives/ng_form';
import * as import31 from '@angular/forms/src/directives/control_container';
import * as import32 from '@angular/forms/src/directives/ng_control_status';
import * as import33 from '../../node_modules/@angular/forms/src/directives/default_value_accessor.ngfactory';
import * as import34 from '../../node_modules/@angular/forms/src/directives/radio_control_value_accessor.ngfactory';
import * as import35 from '../../node_modules/@angular/forms/src/directives/validators.ngfactory';
import * as import36 from '../../node_modules/@angular/forms/src/directives/ng_model.ngfactory';
import * as import37 from '@angular/forms/src/directives/default_value_accessor';
import * as import38 from '@angular/forms/src/directives/validators';
import * as import39 from '@angular/forms/src/validators';
import * as import40 from '@angular/forms/src/directives/control_value_accessor';
import * as import41 from '@angular/forms/src/directives/ng_model';
import * as import42 from '@angular/forms/src/directives/ng_control';
import * as import43 from '../../node_modules/@angular/forms/src/directives/checkbox_value_accessor.ngfactory';
import * as import44 from '@angular/forms/src/directives/checkbox_value_accessor';
class QuizModuleInjector extends import0.NgModuleInjector<import1.QuizModule> {
  _CommonModule_0:import2.CommonModule;
  _InternalFormsSharedModule_1:import3.InternalFormsSharedModule;
  _FormsModule_2:import4.FormsModule;
  _QuizModule_3:import1.QuizModule;
  __NgLocalization_4:import5.NgLocaleLocalization;
  __RadioControlRegistry_5:import6.RadioControlRegistry;
  constructor(parent:import7.Injector) {
    super(parent,([] as any[]),([] as any[]));
  }
  get _NgLocalization_4():import5.NgLocaleLocalization {
    if ((this.__NgLocalization_4 == null)) { (this.__NgLocalization_4 = new import5.NgLocaleLocalization(this.parent.get(import8.LOCALE_ID))); }
    return this.__NgLocalization_4;
  }
  get _RadioControlRegistry_5():import6.RadioControlRegistry {
    if ((this.__RadioControlRegistry_5 == null)) { (this.__RadioControlRegistry_5 = new import6.RadioControlRegistry()); }
    return this.__RadioControlRegistry_5;
  }
  createInternal():import1.QuizModule {
    this._CommonModule_0 = new import2.CommonModule();
    this._InternalFormsSharedModule_1 = new import3.InternalFormsSharedModule();
    this._FormsModule_2 = new import4.FormsModule();
    this._QuizModule_3 = new import1.QuizModule();
    return this._QuizModule_3;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import2.CommonModule)) { return this._CommonModule_0; }
    if ((token === import3.InternalFormsSharedModule)) { return this._InternalFormsSharedModule_1; }
    if ((token === import4.FormsModule)) { return this._FormsModule_2; }
    if ((token === import1.QuizModule)) { return this._QuizModule_3; }
    if ((token === import5.NgLocalization)) { return this._NgLocalization_4; }
    if ((token === import6.RadioControlRegistry)) { return this._RadioControlRegistry_5; }
    return notFoundResult;
  }
  destroyInternal():void {
  }
}
export const QuizModuleNgFactory:import0.NgModuleFactory<import1.QuizModule> = new import0.NgModuleFactory(QuizModuleInjector,import1.QuizModule);
export class Wrapper_Quiz {
  /*private*/ _eventHandler:Function;
  context:import1.Quiz;
  /*private*/ _changed:boolean;
  /*private*/ _expr_0:any;
  constructor() {
    this._changed = false;
    this.context = new import1.Quiz();
    this._expr_0 = import9.UNINITIALIZED;
  }
  ngOnDetach(view:import10.AppView<any>,componentView:import10.AppView<any>,el:any):void {
  }
  ngOnDestroy():void {
  }
  check_data(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import11.checkBinding(throwOnChange,this._expr_0,currValue))) {
      this._changed = true;
      this.context.data = currValue;
      this._expr_0 = currValue;
    }
  }
  ngDoCheck(view:import10.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this._changed;
    this._changed = false;
    if (!throwOnChange) { if ((view.numberOfChecks === 0)) { this.context.ngOnInit(); } }
    return changed;
  }
  checkHost(view:import10.AppView<any>,componentView:import10.AppView<any>,el:any,throwOnChange:boolean):void {
  }
  handleEvent(eventName:string,$event:any):boolean {
    var result:boolean = true;
    return result;
  }
  subscribe(view:import10.AppView<any>,_eventHandler:any):void {
    this._eventHandler = _eventHandler;
  }
}
export class Wrapper_QuizQuestionOptions {
  /*private*/ _eventHandler:Function;
  context:import1.QuizQuestionOptions;
  /*private*/ _changed:boolean;
  /*private*/ _expr_0:any;
  /*private*/ _expr_1:any;
  constructor() {
    this._changed = false;
    this.context = new import1.QuizQuestionOptions();
    this._expr_0 = import9.UNINITIALIZED;
    this._expr_1 = import9.UNINITIALIZED;
  }
  ngOnDetach(view:import10.AppView<any>,componentView:import10.AppView<any>,el:any):void {
  }
  ngOnDestroy():void {
  }
  check_data(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import11.checkBinding(throwOnChange,this._expr_0,currValue))) {
      this._changed = true;
      this.context.data = currValue;
      this._expr_0 = currValue;
    }
  }
  check_index(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import11.checkBinding(throwOnChange,this._expr_1,currValue))) {
      this._changed = true;
      this.context.index = currValue;
      this._expr_1 = currValue;
    }
  }
  ngDoCheck(view:import10.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this._changed;
    this._changed = false;
    if (!throwOnChange) { if ((view.numberOfChecks === 0)) { this.context.ngOnInit(); } }
    return changed;
  }
  checkHost(view:import10.AppView<any>,componentView:import10.AppView<any>,el:any,throwOnChange:boolean):void {
  }
  handleEvent(eventName:string,$event:any):boolean {
    var result:boolean = true;
    return result;
  }
  subscribe(view:import10.AppView<any>,_eventHandler:any):void {
    this._eventHandler = _eventHandler;
  }
}
var renderType_Quiz_Host:import12.RenderComponentType = import11.createRenderComponentType('',0,import13.ViewEncapsulation.None,([] as any[]),{});
class View_Quiz_Host0 extends import10.AppView<any> {
  _el_0:any;
  compView_0:import10.AppView<import1.Quiz>;
  _Quiz_0_3:Wrapper_Quiz;
  constructor(viewUtils:import11.ViewUtils,parentView:import10.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_Quiz_Host0,renderType_Quiz_Host,import14.ViewType.HOST,viewUtils,parentView,parentIndex,parentElement,import15.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import16.ComponentRef<any> {
    this._el_0 = import11.selectOrCreateRenderHostElement(this.renderer,'oe-quiz',import11.EMPTY_INLINE_ARRAY,rootSelector,(null as any));
    this.compView_0 = new View_Quiz0(this.viewUtils,this,0,this._el_0);
    this._Quiz_0_3 = new Wrapper_Quiz();
    this.compView_0.create(this._Quiz_0_3.context);
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [this._el_0]),(null as any));
    return new import16.ComponentRef_<any>(0,this,this._el_0,this._Quiz_0_3.context);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import1.Quiz) && (0 === requestNodeIndex))) { return this._Quiz_0_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._Quiz_0_3.ngDoCheck(this,this._el_0,throwOnChange);
    this.compView_0.internalDetectChanges(throwOnChange);
  }
  destroyInternal():void {
    this.compView_0.destroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
export const QuizNgFactory:import16.ComponentFactory<import1.Quiz> = new import16.ComponentFactory<import1.Quiz>('oe-quiz',View_Quiz_Host0,import1.Quiz);
const styles_Quiz:any[] = ['span.correct[_ngcontent-%COMP%] {\n    	color: #4CAF50;\n    }\n    span.incorrect[_ngcontent-%COMP%] {\n    	color: #F44336;\n    }\n    .pure-form[_ngcontent-%COMP%]   fieldset[_ngcontent-%COMP%] {\n    	border: 0;\n    	padding: 0;\n    }\n    fieldset[_ngcontent-%COMP%]   p[_ngcontent-%COMP%], fieldset[_ngcontent-%COMP%]   ul[_ngcontent-%COMP%] {\n    	max-width: 48rem;\n    }\n      fieldset[_ngcontent-%COMP%]   legend[_ngcontent-%COMP%] {\n        margin-bottom: 1rem;\n        font-weight: bold;\n      }\n    		fieldset[_ngcontent-%COMP%]   div.question[_ngcontent-%COMP%]   p.q-counter[_ngcontent-%COMP%] {\n    			float: left;\n    			width: 3.25rem;\n    			padding-left: 1.25rem;\n    		}\n    	fieldset[_ngcontent-%COMP%]   div.question[_ngcontent-%COMP%]   div.q-body[_ngcontent-%COMP%] {\n    			display: block;\n    			overflow: hidden;\n    		}\n    		fieldset[_ngcontent-%COMP%]   div.question.submitted[_ngcontent-%COMP%]   p.q-counter[_ngcontent-%COMP%] {\n    			padding-left: 0;\n    		}\n    			form.quiz[_ngcontent-%COMP%]   fieldset[_ngcontent-%COMP%]   div.question[_ngcontent-%COMP%]   p.q-counter[_ngcontent-%COMP%]   span.q-grade[_ngcontent-%COMP%] {\n    				float: left;\n    				width: 1rem;\n    				margin-right: .25rem;\n    			}\n    			form.quiz[_ngcontent-%COMP%]   fieldset[_ngcontent-%COMP%]   div.question[_ngcontent-%COMP%]   p.q-counter[_ngcontent-%COMP%], form.quiz[_ngcontent-%COMP%]   fieldset[_ngcontent-%COMP%]   div.question[_ngcontent-%COMP%]   p.q-intro[_ngcontent-%COMP%] {\n    				margin-top: 0;\n    			}\n    			form.quiz[_ngcontent-%COMP%]   div.question[_ngcontent-%COMP%]   p.feedback[_ngcontent-%COMP%] {\n    				margin-top: 0;\n    			}'];
class View_Quiz4 extends import10.AppView<any> {
  _el_0:any;
  _text_1:any;
  constructor(viewUtils:import11.ViewUtils,parentView:import10.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import17.ViewContainer) {
    super(View_Quiz4,renderType_Quiz,import14.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import15.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
  }
  createInternal(rootSelector:string):import16.ComponentRef<any> {
    this._el_0 = import11.createRenderElement(this.renderer,(null as any),'span',new import11.InlineArray2(2,'class','glyph correct animated tada'),(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'',(null as any));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1
    ]
    ),(null as any));
    return (null as any);
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
class View_Quiz5 extends import10.AppView<any> {
  _el_0:any;
  _text_1:any;
  constructor(viewUtils:import11.ViewUtils,parentView:import10.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import17.ViewContainer) {
    super(View_Quiz5,renderType_Quiz,import14.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import15.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
  }
  createInternal(rootSelector:string):import16.ComponentRef<any> {
    this._el_0 = import11.createRenderElement(this.renderer,(null as any),'span',new import11.InlineArray2(2,'class','glyph incorrect animated wobble'),(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'',(null as any));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1
    ]
    ),(null as any));
    return (null as any);
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
class View_Quiz3 extends import10.AppView<any> {
  _el_0:any;
  _text_1:any;
  _anchor_2:any;
  /*private*/ _vc_2:import17.ViewContainer;
  _TemplateRef_2_5:any;
  _NgIf_2_6:import18.Wrapper_NgIf;
  _text_3:any;
  _anchor_4:any;
  /*private*/ _vc_4:import17.ViewContainer;
  _TemplateRef_4_5:any;
  _NgIf_4_6:import18.Wrapper_NgIf;
  _text_5:any;
  constructor(viewUtils:import11.ViewUtils,parentView:import10.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import17.ViewContainer) {
    super(View_Quiz3,renderType_Quiz,import14.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import15.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
  }
  createInternal(rootSelector:string):import16.ComponentRef<any> {
    this._el_0 = import11.createRenderElement(this.renderer,(null as any),'span',new import11.InlineArray2(2,'class','q-grade'),(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n              ',(null as any));
    this._anchor_2 = this.renderer.createTemplateAnchor(this._el_0,(null as any));
    this._vc_2 = new import17.ViewContainer(2,0,this,this._anchor_2);
    this._TemplateRef_2_5 = new import19.TemplateRef_(this,2,this._anchor_2);
    this._NgIf_2_6 = new import18.Wrapper_NgIf(this._vc_2.vcRef,this._TemplateRef_2_5);
    this._text_3 = this.renderer.createText(this._el_0,'\n              ',(null as any));
    this._anchor_4 = this.renderer.createTemplateAnchor(this._el_0,(null as any));
    this._vc_4 = new import17.ViewContainer(4,0,this,this._anchor_4);
    this._TemplateRef_4_5 = new import19.TemplateRef_(this,4,this._anchor_4);
    this._NgIf_4_6 = new import18.Wrapper_NgIf(this._vc_4.vcRef,this._TemplateRef_4_5);
    this._text_5 = this.renderer.createText(this._el_0,'\n            ',(null as any));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._anchor_2,
      this._text_3,
      this._anchor_4,
      this._text_5
    ]
    ),(null as any));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import19.TemplateRef) && (2 === requestNodeIndex))) { return this._TemplateRef_2_5; }
    if (((token === import20.NgIf) && (2 === requestNodeIndex))) { return this._NgIf_2_6.context; }
    if (((token === import19.TemplateRef) && (4 === requestNodeIndex))) { return this._TemplateRef_4_5; }
    if (((token === import20.NgIf) && (4 === requestNodeIndex))) { return this._NgIf_4_6.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_2_0_0:any = this.parentView.context.$implicit.correct;
    this._NgIf_2_6.check_ngIf(currVal_2_0_0,throwOnChange,false);
    this._NgIf_2_6.ngDoCheck(this,this._anchor_2,throwOnChange);
    const currVal_4_0_0:boolean = !this.parentView.context.$implicit.correct;
    this._NgIf_4_6.check_ngIf(currVal_4_0_0,throwOnChange,false);
    this._NgIf_4_6.ngDoCheck(this,this._anchor_4,throwOnChange);
    this._vc_2.detectChangesInNestedViews(throwOnChange);
    this._vc_4.detectChangesInNestedViews(throwOnChange);
  }
  destroyInternal():void {
    this._vc_2.destroyNestedViews();
    this._vc_4.destroyNestedViews();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
  createEmbeddedViewInternal(nodeIndex:number):import10.AppView<any> {
    if ((nodeIndex == 2)) { return new View_Quiz4(this.viewUtils,this,2,this._anchor_2,this._vc_2); }
    if ((nodeIndex == 4)) { return new View_Quiz5(this.viewUtils,this,4,this._anchor_4,this._vc_4); }
    return (null as any);
  }
}
class View_Quiz6 extends import10.AppView<any> {
  _el_0:any;
  compView_0:import10.AppView<import1.QuizQuestionOptions>;
  _QuizQuestionOptions_0_3:Wrapper_QuizQuestionOptions;
  constructor(viewUtils:import11.ViewUtils,parentView:import10.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import17.ViewContainer) {
    super(View_Quiz6,renderType_Quiz,import14.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import15.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
  }
  createInternal(rootSelector:string):import16.ComponentRef<any> {
    this._el_0 = import11.createRenderElement(this.renderer,(null as any),'question-options',import11.EMPTY_INLINE_ARRAY,(null as any));
    this.compView_0 = new View_QuizQuestionOptions0(this.viewUtils,this,0,this._el_0);
    this._QuizQuestionOptions_0_3 = new Wrapper_QuizQuestionOptions();
    this.compView_0.create(this._QuizQuestionOptions_0_3.context);
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [this._el_0]),(null as any));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import1.QuizQuestionOptions) && (0 === requestNodeIndex))) { return this._QuizQuestionOptions_0_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_0_0_0:any = this.parentView.context.$implicit;
    this._QuizQuestionOptions_0_3.check_data(currVal_0_0_0,throwOnChange,false);
    const currVal_0_0_1:any = ((this.parentView.parentView.context.index.toString() + '-') + this.parentView.context.index.toString());
    this._QuizQuestionOptions_0_3.check_index(currVal_0_0_1,throwOnChange,false);
    this._QuizQuestionOptions_0_3.ngDoCheck(this,this._el_0,throwOnChange);
    this.compView_0.internalDetectChanges(throwOnChange);
  }
  destroyInternal():void {
    this.compView_0.destroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
class View_Quiz8 extends import10.AppView<any> {
  _el_0:any;
  _el_1:any;
  _text_2:any;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  /*private*/ _expr_6:any;
  constructor(viewUtils:import11.ViewUtils,parentView:import10.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import17.ViewContainer) {
    super(View_Quiz8,renderType_Quiz,import14.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import15.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
    this._expr_6 = import9.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import16.ComponentRef<any> {
    this._el_0 = import11.createRenderElement(this.renderer,(null as any),'span',import11.EMPTY_INLINE_ARRAY,(null as any));
    this._el_1 = import11.createRenderElement(this.renderer,this._el_0,'strong',import11.EMPTY_INLINE_ARRAY,(null as any));
    this._text_2 = this.renderer.createText(this._el_1,'Feedback:',(null as any));
    this._text_3 = this.renderer.createText(this._el_0,' ',(null as any));
    this._el_4 = import11.createRenderElement(this.renderer,this._el_0,'em',import11.EMPTY_INLINE_ARRAY,(null as any));
    this._text_5 = this.renderer.createText(this._el_4,'',(null as any));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._el_1,
      this._text_2,
      this._text_3,
      this._el_4,
      this._text_5
    ]
    ),(null as any));
    return (null as any);
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_6:any = import11.inlineInterpolate(1,'',this.parentView.parentView.context.$implicit.feedback,'');
    if (import11.checkBinding(throwOnChange,this._expr_6,currVal_6)) {
      this.renderer.setText(this._text_5,currVal_6);
      this._expr_6 = currVal_6;
    }
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
class View_Quiz7 extends import10.AppView<any> {
  _el_0:any;
  _text_1:any;
  _anchor_2:any;
  /*private*/ _vc_2:import17.ViewContainer;
  _TemplateRef_2_5:any;
  _NgIf_2_6:import18.Wrapper_NgIf;
  _text_3:any;
  constructor(viewUtils:import11.ViewUtils,parentView:import10.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import17.ViewContainer) {
    super(View_Quiz7,renderType_Quiz,import14.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import15.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
  }
  createInternal(rootSelector:string):import16.ComponentRef<any> {
    this._el_0 = import11.createRenderElement(this.renderer,(null as any),'p',new import11.InlineArray2(2,'class','feedback'),(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n              ',(null as any));
    this._anchor_2 = this.renderer.createTemplateAnchor(this._el_0,(null as any));
    this._vc_2 = new import17.ViewContainer(2,0,this,this._anchor_2);
    this._TemplateRef_2_5 = new import19.TemplateRef_(this,2,this._anchor_2);
    this._NgIf_2_6 = new import18.Wrapper_NgIf(this._vc_2.vcRef,this._TemplateRef_2_5);
    this._text_3 = this.renderer.createText(this._el_0,'\n            ',(null as any));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._anchor_2,
      this._text_3
    ]
    ),(null as any));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import19.TemplateRef) && (2 === requestNodeIndex))) { return this._TemplateRef_2_5; }
    if (((token === import20.NgIf) && (2 === requestNodeIndex))) { return this._NgIf_2_6.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_2_0_0:any = this.parentView.context.$implicit.submitted;
    this._NgIf_2_6.check_ngIf(currVal_2_0_0,throwOnChange,false);
    this._NgIf_2_6.ngDoCheck(this,this._anchor_2,throwOnChange);
    this._vc_2.detectChangesInNestedViews(throwOnChange);
  }
  destroyInternal():void {
    this._vc_2.destroyNestedViews();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
  createEmbeddedViewInternal(nodeIndex:number):import10.AppView<any> {
    if ((nodeIndex == 2)) { return new View_Quiz8(this.viewUtils,this,2,this._anchor_2,this._vc_2); }
    return (null as any);
  }
}
class View_Quiz2 extends import10.AppView<any> {
  _el_0:any;
  _NgClass_0_3:import21.Wrapper_NgClass;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _anchor_4:any;
  /*private*/ _vc_4:import17.ViewContainer;
  _TemplateRef_4_5:any;
  _NgIf_4_6:import18.Wrapper_NgIf;
  _text_5:any;
  _el_6:any;
  _text_7:any;
  _text_8:any;
  _text_9:any;
  _el_10:any;
  _text_11:any;
  _el_12:any;
  _text_13:any;
  _text_14:any;
  _anchor_15:any;
  /*private*/ _vc_15:import17.ViewContainer;
  _TemplateRef_15_5:any;
  _NgIf_15_6:import18.Wrapper_NgIf;
  _text_16:any;
  _anchor_17:any;
  /*private*/ _vc_17:import17.ViewContainer;
  _TemplateRef_17_5:any;
  _NgIf_17_6:import18.Wrapper_NgIf;
  _text_18:any;
  _text_19:any;
  _map_30:any;
  /*private*/ _expr_31:any;
  /*private*/ _expr_32:any;
  constructor(viewUtils:import11.ViewUtils,parentView:import10.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import17.ViewContainer) {
    super(View_Quiz2,renderType_Quiz,import14.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import15.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
    this._map_30 = import11.pureProxy1((p0:any):{[key: string]:any} => {
      return {submitted: p0};
    });
    this._expr_31 = import9.UNINITIALIZED;
    this._expr_32 = import9.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import16.ComponentRef<any> {
    this._el_0 = import11.createRenderElement(this.renderer,(null as any),'div',new import11.InlineArray2(2,'class','question'),(null as any));
    this._NgClass_0_3 = new import21.Wrapper_NgClass(this.parentView.parentView.parentView.injectorGet(import22.IterableDiffers,this.parentView.parentView.parentIndex),this.parentView.parentView.parentView.injectorGet(import23.KeyValueDiffers,this.parentView.parentView.parentIndex),new import24.ElementRef(this._el_0),this.renderer);
    this._text_1 = this.renderer.createText(this._el_0,'\n          ',(null as any));
    this._el_2 = import11.createRenderElement(this.renderer,this._el_0,'p',new import11.InlineArray2(2,'class','q-counter'),(null as any));
    this._text_3 = this.renderer.createText(this._el_2,'\n            ',(null as any));
    this._anchor_4 = this.renderer.createTemplateAnchor(this._el_2,(null as any));
    this._vc_4 = new import17.ViewContainer(4,2,this,this._anchor_4);
    this._TemplateRef_4_5 = new import19.TemplateRef_(this,4,this._anchor_4);
    this._NgIf_4_6 = new import18.Wrapper_NgIf(this._vc_4.vcRef,this._TemplateRef_4_5);
    this._text_5 = this.renderer.createText(this._el_2,'\n            ',(null as any));
    this._el_6 = import11.createRenderElement(this.renderer,this._el_2,'span',import11.EMPTY_INLINE_ARRAY,(null as any));
    this._text_7 = this.renderer.createText(this._el_6,'',(null as any));
    this._text_8 = this.renderer.createText(this._el_2,'\n          ',(null as any));
    this._text_9 = this.renderer.createText(this._el_0,'\n          ',(null as any));
    this._el_10 = import11.createRenderElement(this.renderer,this._el_0,'div',new import11.InlineArray2(2,'class','q-body'),(null as any));
    this._text_11 = this.renderer.createText(this._el_10,'\n            ',(null as any));
    this._el_12 = import11.createRenderElement(this.renderer,this._el_10,'p',new import11.InlineArray2(2,'class','q-intro'),(null as any));
    this._text_13 = this.renderer.createText(this._el_12,'',(null as any));
    this._text_14 = this.renderer.createText(this._el_10,'\n            ',(null as any));
    this._anchor_15 = this.renderer.createTemplateAnchor(this._el_10,(null as any));
    this._vc_15 = new import17.ViewContainer(15,10,this,this._anchor_15);
    this._TemplateRef_15_5 = new import19.TemplateRef_(this,15,this._anchor_15);
    this._NgIf_15_6 = new import18.Wrapper_NgIf(this._vc_15.vcRef,this._TemplateRef_15_5);
    this._text_16 = this.renderer.createText(this._el_10,'\n            ',(null as any));
    this._anchor_17 = this.renderer.createTemplateAnchor(this._el_10,(null as any));
    this._vc_17 = new import17.ViewContainer(17,10,this,this._anchor_17);
    this._TemplateRef_17_5 = new import19.TemplateRef_(this,17,this._anchor_17);
    this._NgIf_17_6 = new import18.Wrapper_NgIf(this._vc_17.vcRef,this._TemplateRef_17_5);
    this._text_18 = this.renderer.createText(this._el_10,'\n          ',(null as any));
    this._text_19 = this.renderer.createText(this._el_0,'\n        ',(null as any));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._anchor_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._text_8,
      this._text_9,
      this._el_10,
      this._text_11,
      this._el_12,
      this._text_13,
      this._text_14,
      this._anchor_15,
      this._text_16,
      this._anchor_17,
      this._text_18,
      this._text_19
    ]
    ),(null as any));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import19.TemplateRef) && (4 === requestNodeIndex))) { return this._TemplateRef_4_5; }
    if (((token === import20.NgIf) && (4 === requestNodeIndex))) { return this._NgIf_4_6.context; }
    if (((token === import19.TemplateRef) && (15 === requestNodeIndex))) { return this._TemplateRef_15_5; }
    if (((token === import20.NgIf) && (15 === requestNodeIndex))) { return this._NgIf_15_6.context; }
    if (((token === import19.TemplateRef) && (17 === requestNodeIndex))) { return this._TemplateRef_17_5; }
    if (((token === import20.NgIf) && (17 === requestNodeIndex))) { return this._NgIf_17_6.context; }
    if (((token === import25.NgClass) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 19)))) { return this._NgClass_0_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_0_0_0:any = 'question';
    this._NgClass_0_3.check_klass(currVal_0_0_0,throwOnChange,false);
    const currVal_0_0_1:any = this._map_30(this.context.$implicit.submitted);
    this._NgClass_0_3.check_ngClass(currVal_0_0_1,throwOnChange,false);
    this._NgClass_0_3.ngDoCheck(this,this._el_0,throwOnChange);
    const currVal_4_0_0:any = this.context.$implicit.submitted;
    this._NgIf_4_6.check_ngIf(currVal_4_0_0,throwOnChange,false);
    this._NgIf_4_6.ngDoCheck(this,this._anchor_4,throwOnChange);
    const currVal_15_0_0:any = this.context.$implicit.answerChoices;
    this._NgIf_15_6.check_ngIf(currVal_15_0_0,throwOnChange,false);
    this._NgIf_15_6.ngDoCheck(this,this._anchor_15,throwOnChange);
    const currVal_17_0_0:any = this.context.$implicit.feedback;
    this._NgIf_17_6.check_ngIf(currVal_17_0_0,throwOnChange,false);
    this._NgIf_17_6.ngDoCheck(this,this._anchor_17,throwOnChange);
    this._vc_4.detectChangesInNestedViews(throwOnChange);
    this._vc_15.detectChangesInNestedViews(throwOnChange);
    this._vc_17.detectChangesInNestedViews(throwOnChange);
    const currVal_31:any = import11.inlineInterpolate(1,'',(this.context.index + 1),'.');
    if (import11.checkBinding(throwOnChange,this._expr_31,currVal_31)) {
      this.renderer.setText(this._text_7,currVal_31);
      this._expr_31 = currVal_31;
    }
    const currVal_32:any = import11.inlineInterpolate(1,'\n              ',this.context.$implicit.question,'\n            ');
    if (import11.checkBinding(throwOnChange,this._expr_32,currVal_32)) {
      this.renderer.setText(this._text_13,currVal_32);
      this._expr_32 = currVal_32;
    }
  }
  destroyInternal():void {
    this._vc_4.destroyNestedViews();
    this._vc_15.destroyNestedViews();
    this._vc_17.destroyNestedViews();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
  createEmbeddedViewInternal(nodeIndex:number):import10.AppView<any> {
    if ((nodeIndex == 4)) { return new View_Quiz3(this.viewUtils,this,4,this._anchor_4,this._vc_4); }
    if ((nodeIndex == 15)) { return new View_Quiz6(this.viewUtils,this,15,this._anchor_15,this._vc_15); }
    if ((nodeIndex == 17)) { return new View_Quiz7(this.viewUtils,this,17,this._anchor_17,this._vc_17); }
    return (null as any);
  }
}
class View_Quiz1 extends import10.AppView<any> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _text_4:any;
  _anchor_5:any;
  /*private*/ _vc_5:import17.ViewContainer;
  _TemplateRef_5_5:any;
  _NgFor_5_6:import26.Wrapper_NgFor;
  _text_6:any;
  /*private*/ _expr_10:any;
  constructor(viewUtils:import11.ViewUtils,parentView:import10.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import17.ViewContainer) {
    super(View_Quiz1,renderType_Quiz,import14.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import15.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
    this._expr_10 = import9.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import16.ComponentRef<any> {
    this._el_0 = import11.createRenderElement(this.renderer,(null as any),'fieldset',import11.EMPTY_INLINE_ARRAY,(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n        ',(null as any));
    this._el_2 = import11.createRenderElement(this.renderer,this._el_0,'legend',import11.EMPTY_INLINE_ARRAY,(null as any));
    this._text_3 = this.renderer.createText(this._el_2,'',(null as any));
    this._text_4 = this.renderer.createText(this._el_0,'\n        ',(null as any));
    this._anchor_5 = this.renderer.createTemplateAnchor(this._el_0,(null as any));
    this._vc_5 = new import17.ViewContainer(5,0,this,this._anchor_5);
    this._TemplateRef_5_5 = new import19.TemplateRef_(this,5,this._anchor_5);
    this._NgFor_5_6 = new import26.Wrapper_NgFor(this._vc_5.vcRef,this._TemplateRef_5_5,this.parentView.parentView.injectorGet(import22.IterableDiffers,this.parentView.parentIndex),this.parentView.ref);
    this._text_6 = this.renderer.createText(this._el_0,'\n      ',(null as any));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._text_4,
      this._anchor_5,
      this._text_6
    ]
    ),(null as any));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import19.TemplateRef) && (5 === requestNodeIndex))) { return this._TemplateRef_5_5; }
    if (((token === import27.NgFor) && (5 === requestNodeIndex))) { return this._NgFor_5_6.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_5_0_0:any = this.context.$implicit.questions;
    this._NgFor_5_6.check_ngForOf(currVal_5_0_0,throwOnChange,false);
    this._NgFor_5_6.ngDoCheck(this,this._anchor_5,throwOnChange);
    this._vc_5.detectChangesInNestedViews(throwOnChange);
    const currVal_10:any = import11.inlineInterpolate(1,'',this.context.$implicit.intro,'');
    if (import11.checkBinding(throwOnChange,this._expr_10,currVal_10)) {
      this.renderer.setText(this._text_3,currVal_10);
      this._expr_10 = currVal_10;
    }
  }
  destroyInternal():void {
    this._vc_5.destroyNestedViews();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
  createEmbeddedViewInternal(nodeIndex:number):import10.AppView<any> {
    if ((nodeIndex == 5)) { return new View_Quiz2(this.viewUtils,this,5,this._anchor_5,this._vc_5); }
    return (null as any);
  }
}
class View_Quiz9 extends import10.AppView<any> {
  _el_0:any;
  _text_1:any;
  constructor(viewUtils:import11.ViewUtils,parentView:import10.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import17.ViewContainer) {
    super(View_Quiz9,renderType_Quiz,import14.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import15.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
  }
  createInternal(rootSelector:string):import16.ComponentRef<any> {
    this._el_0 = import11.createRenderElement(this.renderer,(null as any),'button',new import11.InlineArray4(4,'class','pure-button','type','submit'),(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'Submit',(null as any));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1
    ]
    ),(null as any));
    return (null as any);
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
class View_Quiz10 extends import10.AppView<any> {
  _el_0:any;
  _text_1:any;
  constructor(viewUtils:import11.ViewUtils,parentView:import10.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import17.ViewContainer) {
    super(View_Quiz10,renderType_Quiz,import14.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import15.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
  }
  createInternal(rootSelector:string):import16.ComponentRef<any> {
    this._el_0 = import11.createRenderElement(this.renderer,(null as any),'button',new import11.InlineArray2(2,'class','pure-button'),(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'Retry',(null as any));
    var disposable_0:Function = import11.subscribeToRenderElement(this,this._el_0,new import11.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_0));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1
    ]
    ),[disposable_0]);
    return (null as any);
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
  handleEvent_0(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'click')) {
      const pd_sub_0:any = ((<any>this.parentView.context.reload()) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
}
class View_Quiz11 extends import10.AppView<any> {
  _el_0:any;
  _text_1:any;
  /*private*/ _expr_2:any;
  constructor(viewUtils:import11.ViewUtils,parentView:import10.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import17.ViewContainer) {
    super(View_Quiz11,renderType_Quiz,import14.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import15.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
    this._expr_2 = import9.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import16.ComponentRef<any> {
    this._el_0 = import11.createRenderElement(this.renderer,(null as any),'p',import11.EMPTY_INLINE_ARRAY,(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'',(null as any));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1
    ]
    ),(null as any));
    return (null as any);
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_2:any = import11.inlineInterpolate(2,'\n      ',this.parentView.context.data.feedback,' You got ',this.parentView.context.data.numberCorrect,' correct.\n    ');
    if (import11.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this.renderer.setText(this._text_1,currVal_2);
      this._expr_2 = currVal_2;
    }
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
var renderType_Quiz:import12.RenderComponentType = import11.createRenderComponentType('',0,import13.ViewEncapsulation.Emulated,styles_Quiz,{});
export class View_Quiz0 extends import10.AppView<import1.Quiz> {
  _text_0:any;
  _el_1:any;
  _NgForm_1_3:import28.Wrapper_NgForm;
  _ControlContainer_1_4:any;
  _NgControlStatusGroup_1_5:import29.Wrapper_NgControlStatusGroup;
  _text_2:any;
  _anchor_3:any;
  /*private*/ _vc_3:import17.ViewContainer;
  _TemplateRef_3_5:any;
  _NgFor_3_6:import26.Wrapper_NgFor;
  _text_4:any;
  _anchor_5:any;
  /*private*/ _vc_5:import17.ViewContainer;
  _TemplateRef_5_5:any;
  _NgIf_5_6:import18.Wrapper_NgIf;
  _text_6:any;
  _text_7:any;
  _anchor_8:any;
  /*private*/ _vc_8:import17.ViewContainer;
  _TemplateRef_8_5:any;
  _NgIf_8_6:import18.Wrapper_NgIf;
  _text_9:any;
  _anchor_10:any;
  /*private*/ _vc_10:import17.ViewContainer;
  _TemplateRef_10_5:any;
  _NgIf_10_6:import18.Wrapper_NgIf;
  _text_11:any;
  constructor(viewUtils:import11.ViewUtils,parentView:import10.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_Quiz0,renderType_Quiz,import14.ViewType.COMPONENT,viewUtils,parentView,parentIndex,parentElement,import15.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import16.ComponentRef<any> {
    const parentRenderNode:any = this.renderer.createViewRoot(this.parentElement);
    this._text_0 = this.renderer.createText(parentRenderNode,'\n    ',(null as any));
    this._el_1 = import11.createRenderElement(this.renderer,parentRenderNode,'form',new import11.InlineArray2(2,'class','pure-form quiz'),(null as any));
    this._NgForm_1_3 = new import28.Wrapper_NgForm((null as any),(null as any));
    this._ControlContainer_1_4 = this._NgForm_1_3.context;
    this._NgControlStatusGroup_1_5 = new import29.Wrapper_NgControlStatusGroup(this._ControlContainer_1_4);
    this._text_2 = this.renderer.createText(this._el_1,'\n      ',(null as any));
    this._anchor_3 = this.renderer.createTemplateAnchor(this._el_1,(null as any));
    this._vc_3 = new import17.ViewContainer(3,1,this,this._anchor_3);
    this._TemplateRef_3_5 = new import19.TemplateRef_(this,3,this._anchor_3);
    this._NgFor_3_6 = new import26.Wrapper_NgFor(this._vc_3.vcRef,this._TemplateRef_3_5,this.parentView.injectorGet(import22.IterableDiffers,this.parentIndex),this.ref);
    this._text_4 = this.renderer.createText(this._el_1,'\n      ',(null as any));
    this._anchor_5 = this.renderer.createTemplateAnchor(this._el_1,(null as any));
    this._vc_5 = new import17.ViewContainer(5,1,this,this._anchor_5);
    this._TemplateRef_5_5 = new import19.TemplateRef_(this,5,this._anchor_5);
    this._NgIf_5_6 = new import18.Wrapper_NgIf(this._vc_5.vcRef,this._TemplateRef_5_5);
    this._text_6 = this.renderer.createText(this._el_1,'\n    ',(null as any));
    this._text_7 = this.renderer.createText(parentRenderNode,'\n    ',(null as any));
    this._anchor_8 = this.renderer.createTemplateAnchor(parentRenderNode,(null as any));
    this._vc_8 = new import17.ViewContainer(8,(null as any),this,this._anchor_8);
    this._TemplateRef_8_5 = new import19.TemplateRef_(this,8,this._anchor_8);
    this._NgIf_8_6 = new import18.Wrapper_NgIf(this._vc_8.vcRef,this._TemplateRef_8_5);
    this._text_9 = this.renderer.createText(parentRenderNode,'\n    ',(null as any));
    this._anchor_10 = this.renderer.createTemplateAnchor(parentRenderNode,(null as any));
    this._vc_10 = new import17.ViewContainer(10,(null as any),this,this._anchor_10);
    this._TemplateRef_10_5 = new import19.TemplateRef_(this,10,this._anchor_10);
    this._NgIf_10_6 = new import18.Wrapper_NgIf(this._vc_10.vcRef,this._TemplateRef_10_5);
    this._text_11 = this.renderer.createText(parentRenderNode,'\n  ',(null as any));
    var disposable_0:Function = import11.subscribeToRenderElement(this,this._el_1,new import11.InlineArray8(6,'ngSubmit',(null as any),'submit',(null as any),'reset',(null as any)),this.eventHandler(this.handleEvent_1));
    this._NgForm_1_3.subscribe(this,this.eventHandler(this.handleEvent_1),true);
    this.init((null as any),((<any>this.renderer).directRenderer? (null as any): [
      this._text_0,
      this._el_1,
      this._text_2,
      this._anchor_3,
      this._text_4,
      this._anchor_5,
      this._text_6,
      this._text_7,
      this._anchor_8,
      this._text_9,
      this._anchor_10,
      this._text_11
    ]
    ),[disposable_0]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import19.TemplateRef) && (3 === requestNodeIndex))) { return this._TemplateRef_3_5; }
    if (((token === import27.NgFor) && (3 === requestNodeIndex))) { return this._NgFor_3_6.context; }
    if (((token === import19.TemplateRef) && (5 === requestNodeIndex))) { return this._TemplateRef_5_5; }
    if (((token === import20.NgIf) && (5 === requestNodeIndex))) { return this._NgIf_5_6.context; }
    if (((token === import30.NgForm) && ((1 <= requestNodeIndex) && (requestNodeIndex <= 6)))) { return this._NgForm_1_3.context; }
    if (((token === import31.ControlContainer) && ((1 <= requestNodeIndex) && (requestNodeIndex <= 6)))) { return this._ControlContainer_1_4; }
    if (((token === import32.NgControlStatusGroup) && ((1 <= requestNodeIndex) && (requestNodeIndex <= 6)))) { return this._NgControlStatusGroup_1_5.context; }
    if (((token === import19.TemplateRef) && (8 === requestNodeIndex))) { return this._TemplateRef_8_5; }
    if (((token === import20.NgIf) && (8 === requestNodeIndex))) { return this._NgIf_8_6.context; }
    if (((token === import19.TemplateRef) && (10 === requestNodeIndex))) { return this._TemplateRef_10_5; }
    if (((token === import20.NgIf) && (10 === requestNodeIndex))) { return this._NgIf_10_6.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._NgForm_1_3.ngDoCheck(this,this._el_1,throwOnChange);
    this._NgControlStatusGroup_1_5.ngDoCheck(this,this._el_1,throwOnChange);
    const currVal_3_0_0:any = this.context.data.sets;
    this._NgFor_3_6.check_ngForOf(currVal_3_0_0,throwOnChange,false);
    this._NgFor_3_6.ngDoCheck(this,this._anchor_3,throwOnChange);
    const currVal_5_0_0:boolean = !this.context.data.inputDisabled;
    this._NgIf_5_6.check_ngIf(currVal_5_0_0,throwOnChange,false);
    this._NgIf_5_6.ngDoCheck(this,this._anchor_5,throwOnChange);
    const currVal_8_0_0:any = this.context.data.inputDisabled;
    this._NgIf_8_6.check_ngIf(currVal_8_0_0,throwOnChange,false);
    this._NgIf_8_6.ngDoCheck(this,this._anchor_8,throwOnChange);
    const currVal_10_0_0:any = this.context.data.inputDisabled;
    this._NgIf_10_6.check_ngIf(currVal_10_0_0,throwOnChange,false);
    this._NgIf_10_6.ngDoCheck(this,this._anchor_10,throwOnChange);
    this._vc_3.detectChangesInNestedViews(throwOnChange);
    this._vc_5.detectChangesInNestedViews(throwOnChange);
    this._vc_8.detectChangesInNestedViews(throwOnChange);
    this._vc_10.detectChangesInNestedViews(throwOnChange);
    this._NgControlStatusGroup_1_5.checkHost(this,this,this._el_1,throwOnChange);
  }
  destroyInternal():void {
    this._vc_3.destroyNestedViews();
    this._vc_5.destroyNestedViews();
    this._vc_8.destroyNestedViews();
    this._vc_10.destroyNestedViews();
    this._NgForm_1_3.ngOnDestroy();
  }
  createEmbeddedViewInternal(nodeIndex:number):import10.AppView<any> {
    if ((nodeIndex == 3)) { return new View_Quiz1(this.viewUtils,this,3,this._anchor_3,this._vc_3); }
    if ((nodeIndex == 5)) { return new View_Quiz9(this.viewUtils,this,5,this._anchor_5,this._vc_5); }
    if ((nodeIndex == 8)) { return new View_Quiz10(this.viewUtils,this,8,this._anchor_8,this._vc_8); }
    if ((nodeIndex == 10)) { return new View_Quiz11(this.viewUtils,this,10,this._anchor_10,this._vc_10); }
    return (null as any);
  }
  handleEvent_1(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._NgForm_1_3.handleEvent(eventName,$event) && result);
    if ((eventName == 'ngSubmit')) {
      const pd_sub_0:any = ((<any>this.context.submitQuiz()) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
}
var renderType_QuizQuestionOptions_Host:import12.RenderComponentType = import11.createRenderComponentType('',0,import13.ViewEncapsulation.None,([] as any[]),{});
class View_QuizQuestionOptions_Host0 extends import10.AppView<any> {
  _el_0:any;
  compView_0:import10.AppView<import1.QuizQuestionOptions>;
  _QuizQuestionOptions_0_3:Wrapper_QuizQuestionOptions;
  constructor(viewUtils:import11.ViewUtils,parentView:import10.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_QuizQuestionOptions_Host0,renderType_QuizQuestionOptions_Host,import14.ViewType.HOST,viewUtils,parentView,parentIndex,parentElement,import15.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import16.ComponentRef<any> {
    this._el_0 = import11.selectOrCreateRenderHostElement(this.renderer,'question-options',import11.EMPTY_INLINE_ARRAY,rootSelector,(null as any));
    this.compView_0 = new View_QuizQuestionOptions0(this.viewUtils,this,0,this._el_0);
    this._QuizQuestionOptions_0_3 = new Wrapper_QuizQuestionOptions();
    this.compView_0.create(this._QuizQuestionOptions_0_3.context);
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [this._el_0]),(null as any));
    return new import16.ComponentRef_<any>(0,this,this._el_0,this._QuizQuestionOptions_0_3.context);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import1.QuizQuestionOptions) && (0 === requestNodeIndex))) { return this._QuizQuestionOptions_0_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._QuizQuestionOptions_0_3.ngDoCheck(this,this._el_0,throwOnChange);
    this.compView_0.internalDetectChanges(throwOnChange);
  }
  destroyInternal():void {
    this.compView_0.destroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
export const QuizQuestionOptionsNgFactory:import16.ComponentFactory<import1.QuizQuestionOptions> = new import16.ComponentFactory<import1.QuizQuestionOptions>('question-options',View_QuizQuestionOptions_Host0,import1.QuizQuestionOptions);
const styles_QuizQuestionOptions:any[] = ['ul[_ngcontent-%COMP%] {\n      list-style-type: none;\n      padding-left: 0;\n    }\n    ul[_ngcontent-%COMP%]   li[_ngcontent-%COMP%] {\n      margin-bottom: .5rem;\n    }\n    ul[_ngcontent-%COMP%]   li[_ngcontent-%COMP%]   input[_ngcontent-%COMP%] {\n      float: left;\n      margin: .375rem .25rem 0 0;\n    }\n    ul[_ngcontent-%COMP%]   li[_ngcontent-%COMP%]   label[_ngcontent-%COMP%] {\n      margin: 0;\n      display: block;\n      overflow: hidden;\n    }\n    input[_ngcontent-%COMP%]:checked    + label[_ngcontent-%COMP%] {\n      font-weight: bold;\n    }\n    .question.submitted[_nghost-%COMP%]   label.answer[_ngcontent-%COMP%], .question.submitted   [_nghost-%COMP%]   label.answer[_ngcontent-%COMP%] {\n      font-style: italic;\n    }'];
class View_QuizQuestionOptions2 extends import10.AppView<any> {
  _el_0:any;
  _DefaultValueAccessor_0_3:import33.Wrapper_DefaultValueAccessor;
  _RadioControlValueAccessor_0_4:import34.Wrapper_RadioControlValueAccessor;
  _RequiredValidator_0_5:import35.Wrapper_RequiredValidator;
  _NG_VALIDATORS_0_6:any[];
  _NG_VALUE_ACCESSOR_0_7:any[];
  _NgModel_0_8:import36.Wrapper_NgModel;
  _NgControl_0_9:any;
  _NgControlStatus_0_10:import29.Wrapper_NgControlStatus;
  /*private*/ _expr_9:any;
  constructor(viewUtils:import11.ViewUtils,parentView:import10.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import17.ViewContainer) {
    super(View_QuizQuestionOptions2,renderType_QuizQuestionOptions,import14.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import15.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
    this._expr_9 = import9.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import16.ComponentRef<any> {
    this._el_0 = import11.createRenderElement(this.renderer,(null as any),'input',new import11.InlineArray4(4,'required','','type','radio'),(null as any));
    this._DefaultValueAccessor_0_3 = new import33.Wrapper_DefaultValueAccessor(this.renderer,new import24.ElementRef(this._el_0));
    this._RadioControlValueAccessor_0_4 = new import34.Wrapper_RadioControlValueAccessor(this.renderer,new import24.ElementRef(this._el_0),this.parentView.parentView.parentView.injectorGet(import6.RadioControlRegistry,this.parentView.parentView.parentIndex),this.injector(0));
    this._RequiredValidator_0_5 = new import35.Wrapper_RequiredValidator();
    this._NG_VALIDATORS_0_6 = [this._RequiredValidator_0_5.context];
    this._NG_VALUE_ACCESSOR_0_7 = [
      this._DefaultValueAccessor_0_3.context,
      this._RadioControlValueAccessor_0_4.context
    ]
    ;
    this._NgModel_0_8 = new import36.Wrapper_NgModel((null as any),this._NG_VALIDATORS_0_6,(null as any),this._NG_VALUE_ACCESSOR_0_7);
    this._NgControl_0_9 = this._NgModel_0_8.context;
    this._NgControlStatus_0_10 = new import29.Wrapper_NgControlStatus(this._NgControl_0_9);
    var disposable_0:Function = import11.subscribeToRenderElement(this,this._el_0,new import11.InlineArray8(8,'ngModelChange',(null as any),'input',(null as any),'blur',(null as any),'change',(null as any)),this.eventHandler(this.handleEvent_0));
    this._NgModel_0_8.subscribe(this,this.eventHandler(this.handleEvent_0),true);
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [this._el_0]),[disposable_0]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import37.DefaultValueAccessor) && (0 === requestNodeIndex))) { return this._DefaultValueAccessor_0_3.context; }
    if (((token === import6.RadioControlValueAccessor) && (0 === requestNodeIndex))) { return this._RadioControlValueAccessor_0_4.context; }
    if (((token === import38.RequiredValidator) && (0 === requestNodeIndex))) { return this._RequiredValidator_0_5.context; }
    if (((token === import39.NG_VALIDATORS) && (0 === requestNodeIndex))) { return this._NG_VALIDATORS_0_6; }
    if (((token === import40.NG_VALUE_ACCESSOR) && (0 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_0_7; }
    if (((token === import41.NgModel) && (0 === requestNodeIndex))) { return this._NgModel_0_8.context; }
    if (((token === import42.NgControl) && (0 === requestNodeIndex))) { return this._NgControl_0_9; }
    if (((token === import32.NgControlStatus) && (0 === requestNodeIndex))) { return this._NgControlStatus_0_10.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._DefaultValueAccessor_0_3.ngDoCheck(this,this._el_0,throwOnChange);
    const currVal_0_1_0:any = this.parentView.parentView.context.index;
    this._RadioControlValueAccessor_0_4.check_name(currVal_0_1_0,throwOnChange,false);
    const currVal_0_1_1:any = this.parentView.context.$implicit;
    this._RadioControlValueAccessor_0_4.check_value(currVal_0_1_1,throwOnChange,false);
    this._RadioControlValueAccessor_0_4.ngDoCheck(this,this._el_0,throwOnChange);
    const currVal_0_2_0:any = '';
    this._RequiredValidator_0_5.check_required(currVal_0_2_0,throwOnChange,false);
    this._RequiredValidator_0_5.ngDoCheck(this,this._el_0,throwOnChange);
    const currVal_0_3_0:any = this.parentView.parentView.context.index;
    this._NgModel_0_8.check_name(currVal_0_3_0,throwOnChange,false);
    const currVal_0_3_1:any = this.parentView.parentView.context.data.submitted;
    this._NgModel_0_8.check_isDisabled(currVal_0_3_1,throwOnChange,false);
    const currVal_0_3_2:any = this.parentView.parentView.context.data.input;
    this._NgModel_0_8.check_model(currVal_0_3_2,throwOnChange,false);
    this._NgModel_0_8.ngDoCheck(this,this._el_0,throwOnChange);
    this._NgControlStatus_0_10.ngDoCheck(this,this._el_0,throwOnChange);
    const currVal_9:any = ((this.parentView.parentView.context.index + '-') + this.parentView.context.index.toString());
    if (import11.checkBinding(throwOnChange,this._expr_9,currVal_9)) {
      this.renderer.setElementProperty(this._el_0,'id',currVal_9);
      this._expr_9 = currVal_9;
    }
    this._RequiredValidator_0_5.checkHost(this,this,this._el_0,throwOnChange);
    this._NgControlStatus_0_10.checkHost(this,this,this._el_0,throwOnChange);
  }
  destroyInternal():void {
    this._RadioControlValueAccessor_0_4.ngOnDestroy();
    this._NgModel_0_8.ngOnDestroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
  handleEvent_0(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._DefaultValueAccessor_0_3.handleEvent(eventName,$event) && result);
    result = (this._RadioControlValueAccessor_0_4.handleEvent(eventName,$event) && result);
    if ((eventName == 'ngModelChange')) {
      const pd_sub_0:any = ((<any>(this.parentView.parentView.context.data.input = $event)) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
}
class View_QuizQuestionOptions3 extends import10.AppView<any> {
  _el_0:any;
  _CheckboxControlValueAccessor_0_3:import43.Wrapper_CheckboxControlValueAccessor;
  _NG_VALUE_ACCESSOR_0_4:any[];
  _NgModel_0_5:import36.Wrapper_NgModel;
  _NgControl_0_6:any;
  _NgControlStatus_0_7:import29.Wrapper_NgControlStatus;
  /*private*/ _expr_6:any;
  /*private*/ _expr_7:any;
  constructor(viewUtils:import11.ViewUtils,parentView:import10.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import17.ViewContainer) {
    super(View_QuizQuestionOptions3,renderType_QuizQuestionOptions,import14.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import15.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
    this._expr_6 = import9.UNINITIALIZED;
    this._expr_7 = import9.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import16.ComponentRef<any> {
    this._el_0 = import11.createRenderElement(this.renderer,(null as any),'input',new import11.InlineArray2(2,'type','checkbox'),(null as any));
    this._CheckboxControlValueAccessor_0_3 = new import43.Wrapper_CheckboxControlValueAccessor(this.renderer,new import24.ElementRef(this._el_0));
    this._NG_VALUE_ACCESSOR_0_4 = [this._CheckboxControlValueAccessor_0_3.context];
    this._NgModel_0_5 = new import36.Wrapper_NgModel((null as any),(null as any),(null as any),this._NG_VALUE_ACCESSOR_0_4);
    this._NgControl_0_6 = this._NgModel_0_5.context;
    this._NgControlStatus_0_7 = new import29.Wrapper_NgControlStatus(this._NgControl_0_6);
    var disposable_0:Function = import11.subscribeToRenderElement(this,this._el_0,new import11.InlineArray8(6,'ngModelChange',(null as any),'change',(null as any),'blur',(null as any)),this.eventHandler(this.handleEvent_0));
    this._NgModel_0_5.subscribe(this,this.eventHandler(this.handleEvent_0),true);
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [this._el_0]),[disposable_0]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import44.CheckboxControlValueAccessor) && (0 === requestNodeIndex))) { return this._CheckboxControlValueAccessor_0_3.context; }
    if (((token === import40.NG_VALUE_ACCESSOR) && (0 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_0_4; }
    if (((token === import41.NgModel) && (0 === requestNodeIndex))) { return this._NgModel_0_5.context; }
    if (((token === import42.NgControl) && (0 === requestNodeIndex))) { return this._NgControl_0_6; }
    if (((token === import32.NgControlStatus) && (0 === requestNodeIndex))) { return this._NgControlStatus_0_7.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._CheckboxControlValueAccessor_0_3.ngDoCheck(this,this._el_0,throwOnChange);
    const currVal_0_1_0:any = ((this.parentView.parentView.context.index + '-') + this.parentView.context.index.toString());
    this._NgModel_0_5.check_name(currVal_0_1_0,throwOnChange,false);
    const currVal_0_1_1:any = this.parentView.parentView.context.data.submitted;
    this._NgModel_0_5.check_isDisabled(currVal_0_1_1,throwOnChange,false);
    const currVal_0_1_2:any = this.parentView.parentView.context.data.input[this.parentView.context.index];
    this._NgModel_0_5.check_model(currVal_0_1_2,throwOnChange,false);
    this._NgModel_0_5.ngDoCheck(this,this._el_0,throwOnChange);
    this._NgControlStatus_0_7.ngDoCheck(this,this._el_0,throwOnChange);
    const currVal_6:any = ((this.parentView.parentView.context.index + '-') + this.parentView.context.index.toString());
    if (import11.checkBinding(throwOnChange,this._expr_6,currVal_6)) {
      this.renderer.setElementProperty(this._el_0,'id',currVal_6);
      this._expr_6 = currVal_6;
    }
    const currVal_7:any = this.parentView.context.$implicit;
    if (import11.checkBinding(throwOnChange,this._expr_7,currVal_7)) {
      this.renderer.setElementProperty(this._el_0,'value',currVal_7);
      this._expr_7 = currVal_7;
    }
    this._NgControlStatus_0_7.checkHost(this,this,this._el_0,throwOnChange);
  }
  destroyInternal():void {
    this._NgModel_0_5.ngOnDestroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
  handleEvent_0(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._CheckboxControlValueAccessor_0_3.handleEvent(eventName,$event) && result);
    if ((eventName == 'ngModelChange')) {
      const pd_sub_0:any = ((<any>(this.parentView.parentView.context.data.input[this.parentView.context.index] = $event)) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
}
class View_QuizQuestionOptions1 extends import10.AppView<any> {
  _el_0:any;
  _text_1:any;
  _anchor_2:any;
  /*private*/ _vc_2:import17.ViewContainer;
  _TemplateRef_2_5:any;
  _NgIf_2_6:import18.Wrapper_NgIf;
  _text_3:any;
  _anchor_4:any;
  /*private*/ _vc_4:import17.ViewContainer;
  _TemplateRef_4_5:any;
  _NgIf_4_6:import18.Wrapper_NgIf;
  _text_5:any;
  _el_6:any;
  _NgClass_6_3:import21.Wrapper_NgClass;
  _text_7:any;
  _text_8:any;
  /*private*/ _expr_16:any;
  _map_17:any;
  /*private*/ _expr_18:any;
  constructor(viewUtils:import11.ViewUtils,parentView:import10.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import17.ViewContainer) {
    super(View_QuizQuestionOptions1,renderType_QuizQuestionOptions,import14.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import15.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
    this._expr_16 = import9.UNINITIALIZED;
    this._map_17 = import11.pureProxy1((p0:any):{[key: string]:any} => {
      return {answer: p0};
    });
    this._expr_18 = import9.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import16.ComponentRef<any> {
    this._el_0 = import11.createRenderElement(this.renderer,(null as any),'li',import11.EMPTY_INLINE_ARRAY,(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n        ',(null as any));
    this._anchor_2 = this.renderer.createTemplateAnchor(this._el_0,(null as any));
    this._vc_2 = new import17.ViewContainer(2,0,this,this._anchor_2);
    this._TemplateRef_2_5 = new import19.TemplateRef_(this,2,this._anchor_2);
    this._NgIf_2_6 = new import18.Wrapper_NgIf(this._vc_2.vcRef,this._TemplateRef_2_5);
    this._text_3 = this.renderer.createText(this._el_0,'\n        ',(null as any));
    this._anchor_4 = this.renderer.createTemplateAnchor(this._el_0,(null as any));
    this._vc_4 = new import17.ViewContainer(4,0,this,this._anchor_4);
    this._TemplateRef_4_5 = new import19.TemplateRef_(this,4,this._anchor_4);
    this._NgIf_4_6 = new import18.Wrapper_NgIf(this._vc_4.vcRef,this._TemplateRef_4_5);
    this._text_5 = this.renderer.createText(this._el_0,'\n        ',(null as any));
    this._el_6 = import11.createRenderElement(this.renderer,this._el_0,'label',import11.EMPTY_INLINE_ARRAY,(null as any));
    this._NgClass_6_3 = new import21.Wrapper_NgClass(this.parentView.parentView.injectorGet(import22.IterableDiffers,this.parentView.parentIndex),this.parentView.parentView.injectorGet(import23.KeyValueDiffers,this.parentView.parentIndex),new import24.ElementRef(this._el_6),this.renderer);
    this._text_7 = this.renderer.createText(this._el_6,'',(null as any));
    this._text_8 = this.renderer.createText(this._el_0,'\n      ',(null as any));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._anchor_2,
      this._text_3,
      this._anchor_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._text_8
    ]
    ),(null as any));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import19.TemplateRef) && (2 === requestNodeIndex))) { return this._TemplateRef_2_5; }
    if (((token === import20.NgIf) && (2 === requestNodeIndex))) { return this._NgIf_2_6.context; }
    if (((token === import19.TemplateRef) && (4 === requestNodeIndex))) { return this._TemplateRef_4_5; }
    if (((token === import20.NgIf) && (4 === requestNodeIndex))) { return this._NgIf_4_6.context; }
    if (((token === import25.NgClass) && ((6 <= requestNodeIndex) && (requestNodeIndex <= 7)))) { return this._NgClass_6_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_2_0_0:any = (this.parentView.context.data.type === 'radio');
    this._NgIf_2_6.check_ngIf(currVal_2_0_0,throwOnChange,false);
    this._NgIf_2_6.ngDoCheck(this,this._anchor_2,throwOnChange);
    const currVal_4_0_0:any = (this.parentView.context.data.type === 'checkbox');
    this._NgIf_4_6.check_ngIf(currVal_4_0_0,throwOnChange,false);
    this._NgIf_4_6.ngDoCheck(this,this._anchor_4,throwOnChange);
    const currVal_6_0_0:any = this._map_17(this.parentView.context.isAnswer(this.context.$implicit,this.parentView.context.data.answer,this.parentView.context.data.submitted));
    this._NgClass_6_3.check_ngClass(currVal_6_0_0,throwOnChange,false);
    this._NgClass_6_3.ngDoCheck(this,this._el_6,throwOnChange);
    this._vc_2.detectChangesInNestedViews(throwOnChange);
    this._vc_4.detectChangesInNestedViews(throwOnChange);
    const currVal_16:any = ((this.parentView.context.index + '-') + this.context.index.toString());
    if (import11.checkBinding(throwOnChange,this._expr_16,currVal_16)) {
      this.renderer.setElementAttribute(this._el_6,'for',((currVal_16 == null)? (null as any): currVal_16.toString()));
      this._expr_16 = currVal_16;
    }
    const currVal_18:any = import11.inlineInterpolate(1,'',this.context.$implicit,'');
    if (import11.checkBinding(throwOnChange,this._expr_18,currVal_18)) {
      this.renderer.setText(this._text_7,currVal_18);
      this._expr_18 = currVal_18;
    }
  }
  destroyInternal():void {
    this._vc_2.destroyNestedViews();
    this._vc_4.destroyNestedViews();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
  createEmbeddedViewInternal(nodeIndex:number):import10.AppView<any> {
    if ((nodeIndex == 2)) { return new View_QuizQuestionOptions2(this.viewUtils,this,2,this._anchor_2,this._vc_2); }
    if ((nodeIndex == 4)) { return new View_QuizQuestionOptions3(this.viewUtils,this,4,this._anchor_4,this._vc_4); }
    return (null as any);
  }
}
var renderType_QuizQuestionOptions:import12.RenderComponentType = import11.createRenderComponentType('',0,import13.ViewEncapsulation.Emulated,styles_QuizQuestionOptions,{});
export class View_QuizQuestionOptions0 extends import10.AppView<import1.QuizQuestionOptions> {
  _text_0:any;
  _el_1:any;
  _text_2:any;
  _anchor_3:any;
  /*private*/ _vc_3:import17.ViewContainer;
  _TemplateRef_3_5:any;
  _NgFor_3_6:import26.Wrapper_NgFor;
  _text_4:any;
  _text_5:any;
  constructor(viewUtils:import11.ViewUtils,parentView:import10.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_QuizQuestionOptions0,renderType_QuizQuestionOptions,import14.ViewType.COMPONENT,viewUtils,parentView,parentIndex,parentElement,import15.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import16.ComponentRef<any> {
    const parentRenderNode:any = this.renderer.createViewRoot(this.parentElement);
    this._text_0 = this.renderer.createText(parentRenderNode,'\n    ',(null as any));
    this._el_1 = import11.createRenderElement(this.renderer,parentRenderNode,'ul',import11.EMPTY_INLINE_ARRAY,(null as any));
    this._text_2 = this.renderer.createText(this._el_1,'\n      ',(null as any));
    this._anchor_3 = this.renderer.createTemplateAnchor(this._el_1,(null as any));
    this._vc_3 = new import17.ViewContainer(3,1,this,this._anchor_3);
    this._TemplateRef_3_5 = new import19.TemplateRef_(this,3,this._anchor_3);
    this._NgFor_3_6 = new import26.Wrapper_NgFor(this._vc_3.vcRef,this._TemplateRef_3_5,this.parentView.injectorGet(import22.IterableDiffers,this.parentIndex),this.ref);
    this._text_4 = this.renderer.createText(this._el_1,'\n    ',(null as any));
    this._text_5 = this.renderer.createText(parentRenderNode,'\n  ',(null as any));
    this.init((null as any),((<any>this.renderer).directRenderer? (null as any): [
      this._text_0,
      this._el_1,
      this._text_2,
      this._anchor_3,
      this._text_4,
      this._text_5
    ]
    ),(null as any));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import19.TemplateRef) && (3 === requestNodeIndex))) { return this._TemplateRef_3_5; }
    if (((token === import27.NgFor) && (3 === requestNodeIndex))) { return this._NgFor_3_6.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_3_0_0:any = this.context.data.answerChoices;
    this._NgFor_3_6.check_ngForOf(currVal_3_0_0,throwOnChange,false);
    this._NgFor_3_6.ngDoCheck(this,this._anchor_3,throwOnChange);
    this._vc_3.detectChangesInNestedViews(throwOnChange);
  }
  destroyInternal():void {
    this._vc_3.destroyNestedViews();
  }
  createEmbeddedViewInternal(nodeIndex:number):import10.AppView<any> {
    if ((nodeIndex == 3)) { return new View_QuizQuestionOptions1(this.viewUtils,this,3,this._anchor_3,this._vc_3); }
    return (null as any);
  }
}